import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import BottomNav from '@/components/BottomNav'
import { Locale, i18n } from '@/i18n.config'
import Header from '@/components/Header'
import { getDictionary } from '@/lib/dictionary'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  const dict = await getDictionary(lang)
  return (
    <html lang={lang ?? i18n.defaultLocale}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="relative flex flex-col">
          <Header dict={dict} />
          <div className="m-auto flex-1 py-8 prose lg:prose-lg">{children}</div>
          <BottomNav lang={lang} dict={dict.navigation} />
        </div>
      </body>
    </html>
  )
}
